alertmanager:
  enabled: false
  
grafana:
  grafana.ini:
    server:
      domain: "grafana.${domain}"
        # The full public facing url you use in browser, used for redirects and emails
      root_url: "https://grafana.${domain}"

  adminPassword: rmfkvksk1!
  defaultDashboardsTimezone: Asia/Seoul
  ingress:
    enabled: true    
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: "HTTP"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/certificate-arn: "${tls_cert_arn}"
      alb.ingress.kubernetes.io/ssl-redirect: "443"
    hosts:
    - "grafana.${domain}"
    
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    retention: 18d
    retentionSize: 10GiB
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: auto-ebs-sc
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

prometheus-node-exporter:
  prometheus:
    monitor:
      interval: 15s